version: '2.2'
services:
  es01:
    image: elasticsearch:2.3
    container_name: es01
    environment:
      - node.name=es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata01:
    driver: local